////////////////////////////////////////////////////////////////
// BEGIN SECTION GENERATED BY blackbody_color_scale.py

// http://www.vendian.org/mncharity/dir3/blackbody/UnstableURLs/bbr_color.html

#define FIRE_PERIOD 10
#define FIRE_CHANGE_COUNT 30

#define BLACKBODY_COUNT 52
// the following makes a dreceasing random distribution
#define GET_BLACKBODY_INDEX ((random(73) * random(73)) / 100) % BLACKBODY_COUNT

const rgb_color blackbody[] = {{3,0,0},{12,0,0},{21,0,0},{30,0,0},{39,0,0},{48,0,0},{57,0,0},{66,0,0},{75,0,0},{84,0,0},{93,0,0},{102,0,0},{111,0,0},{120,0,0},{129,0,0},{138,0,0},{147,0,0},{156,0,0},{165,0,0},{174,0,0},{183,0,0},{192,0,0},{201,0,0},{210,6,0},{219,15,0},{228,24,0},{237,33,0},{246,42,0},{255,51,0},{255,51,0},{255,69,0},{255,82,0},{255,93,0},{255,102,0},{255,111,0},{255,118,0},{255,124,0},{255,130,0},{255,135,0},{255,141,11},{255,146,29},{255,152,41},{255,157,51},{255,162,60},{255,166,69},{255,170,77},{255,174,84},{255,178,91},{255,182,98},{255,185,105},{255,189,111},{255,192,118}};

unsigned long last_fire;

// END SECTION GENERATED BY blackbody_color_scale.py
////////////////////////////////////////////////////////////////
